site_name: MY_DOCS
theme:
  name: material
  font: false
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      accent: pink
      primary: black
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      accent: pink
      primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - header.autohide
    - search.highlight
    - search.suggest
    - navigation.top
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.snippets
  - pymdownx.details
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - search:
      lang:
        - en
        - ja